[package]
name = "toolkit"
version = "0.1.0"
authors = ["Yakov Borevich <j.borevich@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
zip = "0.5"
walkdir = "2.3.1"
