name: toolkit-windows
on: push
jobs:
  build-toolkit-win:
    runs-on: ubuntu-latest
    steps:
      - name: Install mingw
        run: sudo apt-get install gcc-mingw-w64
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            toolkit/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-gnu --manifest-path=toolkit/Cargo.toml
      - name: Show content
        run: find .
      - name: Upload library
        uses: actions/upload-artifact@v2
        with:
          name: toolkit.win
          path: toolkit/target/x86_64-pc-windows-gnu/release/toolkit.exe